# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 */6 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: moshemoshe137
          template: classic
          base: repositories, metadata
          base_indepth: yes
          config_timezone: America/Chicago
          plugin_calendar: yes
          plugin_calendar_limit: 2
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_from: 1000
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_languages: yes
          plugin_languages_skipped:
            moshemoshe137/LS-Math-Resources, moshemoshe137/CSIS-Resources
          plugin_languages_ignored: HTML
          plugin_languages_aliases: Jupyter Notebook:Python, PLpgSQL:PLSQL, SQL:PLSQL
          plugin_languages_details: bytes-size, percentage, lines
          plugin_languages_analysis_timeout: 60
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 0
          plugin_languages_recent_load: 1000
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_lines_history_limit: 0
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          repositories_affiliations: owner,collaborator
          repositories_skipped: github-slideshow,myappsample
